site_name: Research to Startup
site_url: https://startups.berkeley.edu
repo_url: https://github.com/sergeyk/research-to-startup
repo_name: GitHub

site_description:
site_author: Research to Startup
copyright: Research to Startup, 2022
# google_analytics:
#   - UA-118687450-1
#   - auto

theme:
  name: material
  features:
    - navigation.tabs
    # - navigation.sections
#   custom_dir: overrides
#   favicon: images/favicon.png
#   font: false
#   logo: images/favicon.png

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.superfences

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/research_to_startup
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/c/ResearchToStartup

nav:
  - 'Home': 'index.md'
  # - 'Project Guidelines': 'project.md'
